version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: google-docs-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: google-docs-clone
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    container_name: google-docs-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MONGODB_URI=mongodb://mongodb:27017/google-docs-clone
      - CLIENT_URL=http://localhost:3000
      - REACT_APP_SERVER_URL=http://localhost:3001
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:
